- name: Install docker.io
  apt:
    name: docker.io
    update_cache: yes

- name: Create docker directory
  file:
    path: /home/magento/docker
    owner: magento
    group: docker
    mode: 0550
    state: directory

- name: Add user to docker group
  user:
    name: magento
    groups: docker
    append: yes