FROM node:alpine3.11

USER root

RUN apk update
RUN apk add bash \
            python \
            python3 \
            curl \
            openssl \
            git \
            build-base \
            sudo


RUN addgroup --gid {{ group_gid }} {{ user_group }}
RUN adduser  {{ user_name }} --uid {{ user_uid }}  -G {{ user_group }} --disabled-password
RUN echo "{{ user_name }}:{{ user_group }}" | chpasswd

# --- Add user to sudoers
RUN echo "{{ user_name }} ALL=(ALL) ALL" > /etc/sudoers.d/{{ user_name }}
RUN chmod 0440 /etc/sudoers.d/{{ user_name }}
RUN echo "Set disable_coredump false" >> /etc/sudo.conf

RUN npm i -g graphql-cli \
             pm2

USER {{ user_name }}

WORKDIR {{ frontend_root_dir }}

EXPOSE 3000

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]