- name: Create magento directory
  file:
    path: "{{ backend_root_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0770
    state: directory

- name: Create storefront directory
  file:
    path: "{{ frontend_root_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0770
    state: directory